from pydantic import BaseModel, Field
from typing import Optional

class DrugEventRow(BaseModel):
    top_safetyreportversion: Optional[str] = Field(None, description="Safety report version")
    top_safetyreportid: str = Field(..., description="Unique safety report ID")
    top_primarysourcecountry: Optional[str] = Field(None, description="Primary source country")
    top_occurcountry: Optional[str] = Field(None, description="Country where event occurred")
    top_transmissiondateformat: Optional[str] = Field(None, description="Transmission date format code")
    top_transmissiondate: Optional[str] = Field(None, description="Transmission date (YYYYMMDD)")
    top_reporttype: Optional[str] = Field(None, description="Report type code")
    top_serious: Optional[int] = Field(None, description="Seriousness indicator")
    top_receivedateformat: Optional[str] = Field(None, description="Receive date format code")
    top_receivedate: Optional[str] = Field(None, description="Receive date (YYYYMMDD)")
    top_receiptdateformat: Optional[str] = Field(None, description="Receipt date format code")
    top_receiptdate: Optional[str] = Field(None, description="Receipt date (YYYYMMDD)")
    top_fulfillexpeditecriteria: Optional[str] = Field(None, description="Expedite criteria fulfilled")
    top_reportduplicate_duplicatesource: Optional[str] = Field(None, description="Duplicate report source")
    top_primarysource_reportercountry: Optional[str] = Field(None, description="Reporter country")
    top_primarysource_qualification: Optional[str] = Field(None, description="Reporter qualification code")
    top_sender_sendertype: Optional[str] = Field(None, description="Sender type code")
    top_sender_senderorganization: Optional[str] = Field(None, description="Sender organization")
    top_receiver_receivertype: Optional[str] = Field(None, description="Receiver type code")
    top_receiver_receiverorganization: Optional[str] = Field(None, description="Receiver organization")
    patient_patientonsetage: Optional[float] = Field(None, description="Patient onset age")
    patient_patientonsetageunit: Optional[str] = Field(None, description="Patient onset age unit code")
    patient_patientsex: Optional[int] = Field(None, description="Patient sex code")
    patient_summary_narrativeincludeclinical: Optional[str] = Field(None, description="Narrative clinical summary")
    reaction_reactionmeddraversionpt: Optional[str] = Field(None, description="MedDRA version for reaction term")
    reaction_reactionmeddrapt: str = Field(..., description="Reaction MedDRA preferred term")
    drug_drugcharacterization: Optional[str] = Field(None, description="Drug characterization code")
    drug_medicinalproduct: str = Field(..., description="Drug medicinal product name")
    drug_drugstructuredosagenumb: Optional[str] = Field(None, description="Structured dosage number")
    drug_drugstructuredosageunit: Optional[str] = Field(None, description="Structured dosage unit")
    drug_drugseparatedosagenumb: Optional[str] = Field(None, description="Separate dosage number")
    drug_drugintervaldosageunitnumb: Optional[str] = Field(None, description="Interval dosage unit number")
    drug_drugintervaldosagedefinition: Optional[str] = Field(None, description="Interval dosage definition")
    drug_drugadministrationroute: Optional[str] = Field(None, description="Drug administration route code")
    drug_drugindication: Optional[str] = Field(None, description="Drug indication")
    drug_drugstartdateformat: Optional[str] = Field(None, description="Drug start date format code")
    drug_drugstartdate: Optional[str] = Field(None, description="Drug start date (YYYYMMDD)")
    drug_drugenddateformat: Optional[str] = Field(None, description="Drug end date format code")
    drug_drugenddate: Optional[str] = Field(None, description="Drug end date (YYYYMMDD)")
    drug_drugadditional: Optional[str] = Field(None, description="Additional drug information")
    drug_activesubstance_activesubstancename: Optional[str] = Field(None, description="Active substance name")
    drug_openfda_application_number: Optional[str] = Field(None, description="OpenFDA application number")
    drug_openfda_brand_name: Optional[str] = Field(None, description="OpenFDA brand name(s)")
    drug_openfda_generic_name: Optional[str] = Field(None, description="OpenFDA generic name(s)")
    drug_openfda_manufacturer_name: Optional[str] = Field(None, description="OpenFDA manufacturer name(s)")
    drug_openfda_product_ndc: Optional[str] = Field(None, description="OpenFDA product NDC(s)")
    drug_openfda_product_type: Optional[str] = Field(None, description="OpenFDA product type(s)")
    drug_openfda_route: Optional[str] = Field(None, description="OpenFDA route(s)")
    drug_openfda_substance_name: Optional[str] = Field(None, description="OpenFDA substance name(s)")
    drug_openfda_rxcui: Optional[str] = Field(None, description="OpenFDA RxCUI(s)")
    drug_openfda_spl_id: Optional[str] = Field(None, description="OpenFDA SPL ID(s)")
    drug_openfda_spl_set_id: Optional[str] = Field(None, description="OpenFDA SPL Set ID(s)")
    drug_openfda_package_ndc: Optional[str] = Field(None, description="OpenFDA package NDC(s)")
    drug_openfda_nui: Optional[str] = Field(None, description="OpenFDA NUI(s)")
    drug_openfda_pharm_class_epc: Optional[str] = Field(None, description="OpenFDA pharmacologic class EPC(s)")
    drug_openfda_pharm_class_cs: Optional[str] = Field(None, description="OpenFDA pharmacologic class CS(s)")
    drug_openfda_pharm_class_moa: Optional[str] = Field(None, description="OpenFDA pharmacologic class MoA(s)")
    drug_openfda_unii: Optional[str] = Field(None, description="OpenFDA UNII(s)")
    source_drug_name: Optional[str] = Field(None, description="Source drug name (query)")
    drug_drugdosagetext: Optional[str] = Field(None, description="Drug dosage text")
    top_seriousnessdeath: Optional[int] = Field(None, description="Seriousness: death")
    top_seriousnesslifethreatening: Optional[int] = Field(None, description="Seriousness: life-threatening")
    top_seriousnesshospitalization: Optional[int] = Field(None, description="Seriousness: hospitalization")
    top_seriousnessdisabling: Optional[int] = Field(None, description="Seriousness: disabling")
    top_seriousnesscongenitalanomali: Optional[int] = Field(None, description="Seriousness: congenital anomaly")
    top_seriousnessother: Optional[int] = Field(None, description="Seriousness: other")
    top_companynumb: Optional[str] = Field(None, description="Company number")
    patient_patientagegroup: Optional[str] = Field(None, description="Patient age group code")
    reaction_reactionoutcome: Optional[int] = Field(None, description="Reaction outcome code")
    drug_drugdosageform: Optional[str] = Field(None, description="Drug dosage form")
    drug_actiondrug: Optional[str] = Field(None, description="Action drug code")
    drug_drugauthorizationnumb: Optional[str] = Field(None, description="Drug authorization number")
    top_authoritynumb: Optional[str] = Field(None, description="Authority number")
    patient_patientweight: Optional[float] = Field(None, description="Patient weight")
